set_property SRC_FILE_INFO {cfile:/home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0_board.xdc rfile:../../../design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:edt_zcu106_i/axi_gpio_0/U0 prop_thru_buffer:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1_board.xdc rfile:../../../design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1_board.xdc id:2 order:EARLY used_in_board:yes scoped_inst:edt_zcu106_i/axi_gpio_1/U0 prop_thru_buffer:yes} [current_design]
current_instance edt_zcu106_i/axi_gpio_0/U0
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_SW_C} [get_ports gpio_io_i[0]]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_SW_W} [get_ports gpio_io_i[1]]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_SW_S} [get_ports gpio_io_i[2]]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_SW_E} [get_ports gpio_io_i[3]]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_SW_N} [get_ports gpio_io_i[4]]
current_instance
current_instance edt_zcu106_i/axi_gpio_1/U0
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_0_LS} [get_ports gpio_io_o[0]]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_1_LS} [get_ports gpio_io_o[1]]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_2_LS} [get_ports gpio_io_o[2]]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_3_LS} [get_ports gpio_io_o[3]]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_4_LS} [get_ports gpio_io_o[4]]
set_property src_info {type:SCOPED_XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_5_LS} [get_ports gpio_io_o[5]]
set_property src_info {type:SCOPED_XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_6_LS} [get_ports gpio_io_o[6]]
set_property src_info {type:SCOPED_XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {GPIO_LED_7_LS} [get_ports gpio_io_o[7]]
