# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/edt_zcu106/edt_zcu106.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106 || ORIG_REF_NAME==edt_zcu106} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_zynq_ultra_ps_e_0_0/edt_zcu106_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==edt_zcu106_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_axi_timer_0_0/edt_zcu106_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_timer_0_0 || ORIG_REF_NAME==edt_zcu106_axi_timer_0_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_1 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_1} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_xbar_0/edt_zcu106_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_xbar_0 || ORIG_REF_NAME==edt_zcu106_xbar_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_ps8_0_axi_periph_0/edt_zcu106_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_ps8_0_axi_periph_0 || ORIG_REF_NAME==edt_zcu106_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_rst_ps8_0_99M_0/edt_zcu106_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu106_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/edt_zcu106/ip/edt_zcu106_auto_pc_0/edt_zcu106_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==edt_zcu106_auto_pc_0 || ORIG_REF_NAME==edt_zcu106_auto_pc_0} -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_zynq_ultra_ps_e_0_0/edt_zcu106_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_zynq_ultra_ps_e_0_0/edt_zcu106_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==edt_zcu106_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_timer_0_0/edt_zcu106_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_timer_0_0 || ORIG_REF_NAME==edt_zcu106_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_timer_0_0/edt_zcu106_axi_timer_0_0_ooc.xdc

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0_ooc.xdc

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_0/edt_zcu106_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_1 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1_ooc.xdc

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_axi_gpio_0_1/edt_zcu106_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_axi_gpio_0_1 || ORIG_REF_NAME==edt_zcu106_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_rst_ps8_0_99M_0/edt_zcu106_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu106_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_rst_ps8_0_99M_0/edt_zcu106_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu106_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu106_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/ip/edt_zcu106_auto_pc_0/edt_zcu106_auto_pc_0_ooc.xdc

# XDC: /home/jkl-rpu/design_example_1/design_example_1.gen/sources_1/bd/edt_zcu106/edt_zcu106_ooc.xdc
